project: 
  type: website

format:
  html:
    theme:
      light: [cosmo, theme-static/theme.scss] 
      dark: [cosmo, theme-static/theme-dark.scss]

metadata-files:
  - theme-static/_website.yml
  - ./navbars/_topnav_sefsc.yml
  - https://raw.githubusercontent.com/MattGrossi-NOAA/documentation-theme-quarto/navbars/_topnav_sefsc.yml
  - _metadata.yml
