project: 
  type: website

format:
  html:
    theme:
      light: [cosmo, theme/theme.scss] 
      dark: [cosmo, theme/theme-dark.scss]

metadata-files:
  - theme/_website.yml
  - navbars/_topnav_sefsc.yml
  - _metadata.yml
