---
title: Using the Model
subtitle: Predicting the ages of a set of menhaden scale images
metadata-files:
  - ../_metadata.yml
order: 5
---

Running the Menhaden Ageing Model is straightforward and only requires two commands: one to pre-process the images and a second to run the age inference model. You will, however, need to modify a `configurations.yml` file, as [described previously](configuration.qmd). A sample is provided below, while the contents of this file are explained in more detail in the [model options](index.qmd#options).

### Activate the Virtual Environment

First we need to activate the virtual environment we [previously configured](setup.qmd#create-a-virtual-environment). In a terminal window, type:

```bash
conda activate scaleageing
```

:::{.callout-tip}
If you named your virtual environment something other than "scaleageing", invoke that name instead.
:::

### Running the model

Navigate (`cd`) into the directory containing the `predict-ages-multimodal.py` script. If you simply cloned the repo and have not moved anything around, this will in the `/scripts` subdirectory in the cloned repository. For example:

```bash
cd "c:/Users/user.name/Documents/ageing/{{< meta repo.name >}}/scripts"
```

Run the model as described in the [usage instructions](index.qmd#usage):

```bash
python process-images.py --config_path <config_dir>
python predict-ages-multimodal.py --config_path <config_dir>
```

where `<config_dir>` is the path to the configuration file containing model settings presented [above](#configuration-file).

#### Examples

If your `configurations.yml` file is [stored alongside your model script](configuration.qmd#option-1-alongside-the-model), your execution commands will simply be:

```bash
python process-images.py --config_path configurations.yml
python predict-ages-multimodal.py --config_path configurations.yml
```

Or, if you named your configuration file something unique such as `configuration-2024-atl.yml`, it might look like this:

```bash
python process-images.py --config_path configuration-2024-atl.yml
python predict-ages-multimodal.py --config_path configuration-2024-atl.yml
```

Alternatively, your `configurations.yml` file is [stored alongside your data](configuration.qmd#option-2-alongside-the-data), you will need to tell the script exactly where that file is located using its full directory path. Be sure to also include the correct file name, if applicable. For example:

```bash
python process-images.py --config_path "c:/Users/user.name/Documents/data/2024/configurations.yml"
python predict-ages-multimodal.py --config_path "c:/Users/user.name/Documents/data/2024/configurations.yml"
```

::: {.callout-tip}
If you get a "File not found" error when running the script, carefully check your directories and file names, including those contained in the configuration file.
:::

### When finished

When you are finished running the model, deactivate the virtual environment to free up resources on your computer:

```bash
conda deactivate
```

Note that there is no need to specify the environment when deactivating, as conda automatically deactivates the running environment.